services:

  moodle:
    image: bitnami/moodle:4

    environment:
      - MOODLE_DATABASE_TYPE=${MOODLE_DATABASE_TYPE:-pgsql}
      - MOODLE_DATABASE_HOST=${MOODLE_DATABASE_HOST}
      - MOODLE_DATABASE_USER=${MOODLE_DATABASE_USER}
      - MOODLE_DATABASE_PASSWORD=${MOODLE_DATABASE_PASSWORD}
      - MOODLE_DATABASE_NAME=${MOODLE_DATABASE_NAME}
      - MOODLE_DATABASE_PORT_NUMBER=${MOODLE_DATABASE_PORT_NUMBER:-5432}
      - MOODLE_HOST=${MOODLE_HOST}
      - MOODLE_SSLPROXY=${MOODLE_SSLPROXY:-true}

    labels:
      - traefik.http.services.moodle.loadbalancer.server.port=8080
      - traefik.enable=true
      - traefik.http.routers.moodle.tls=true
      - traefik.http.routers.moodle.tls.certresolver=myresolver
      - traefik.http.routers.moodle.rule=Host(`${MOODLE_HOST}`)
      
    volumes:
      - moodle_data:/bitnami/moodle
      - moodledata_data:/bitnami/moodledata

volumes:

  moodle_data:
    driver: local
  moodledata_data:
    driver: local

networks:
  default:
    name: bonde